### ISSUE TITLE
Disallow duplicate old-path links

### ISSUE THREAD

**Issue by jonaslu** [Sydsvenskan/doc_format#1]
We have documents (e g  `ecd13265-745c-5c36-9e17-d324f122b98d` in OC prod) where there are duplicate old-path links:
```
        {
            "rel": "old-path",
            "url": "2016-10-28/fbi-aterupptar-utredning-mot-clinton"
        },
        {
            "rel": "old-path",
            "url": "2016-10-28/fbi-granskar-clinton--trump-jublar"
        },
```
This should be dissallowed - also traverse the stored documents and delete the duplicate links.

**Comment by marcelsvensson** [comment]
I'll tag myself here (from this comment) as this was an intended design choice back in the day - keeping every older path on a document for redirecting to the newer.

This is at least what the path-plugin does in the writer.

**Comment by slm-marvan** [comment]
I was also given the impression that the recommend practice is to keep old paths coupled to the document.

As a side note: during a recent discussion with Naviga the usage of `originalUrl` was recommended as a property in the context of importing legacy content into OC. As @marcelsvensson mentioned the reason here being the ability to setup redirects. Wondering if usage of `originalUrl` could come to conflict with usage of `old-path` here?

```xml
<itemMetaExtProperty type="imext:originalUrl" value=”http://url.com/>
```

Standardising on some sort of non-canonical URLs collection for documents may be what is actually needed to address this?

**Comment by jonaslu** [comment]
Uh, I just saw my data had been truncated. It's actual duplicate data (as in the exact same entry appearing twice in the the array):
```
        },
        {
            "rel": "old-path",
            "url": "2016-10-28/fbi-granskar-clinton--trump-jublar"
        },
        ...
        {
            "rel": "old-path",
            "url": "2016-10-28/fbi-granskar-clinton--trump-jublar"
        },
```

But I'll close this and move elsewhere for now until we know how big this is. @slm-marvan Didn't quite get that but feel free to open another issue if you want to discuss that case so we'll keep issues focused on one thing.
